version: '3'

services:

  odoo:
    
    image: odoo:17.0

    env_file: .env

    depends_on:
    
      - postgres

    ports:
    
      - "8069:8069"
    
    volumes:
    
      - data:/var/lib/odoo

  postgres:

    image: postgres:latest

    env_file: .env

    volumes:
    
      - db:/var/lib/postgresql@17/data/pgdata
    
volumes:

  data:

  db:
